In [30]:
import numpy as np

In [31]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr[5]

5

In [33]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [34]:
arr[:5]

array([0, 1, 2, 3, 4])

In [35]:
arr[5:]

array([5, 6, 7, 8, 9])

In [36]:
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
slice_of_arr = arr[:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [38]:
slice_of_arr[:] = 100
slice_of_arr

array([100, 100, 100, 100, 100])

In [39]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [44]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr_copy = arr.copy()
arr_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr_copy[:4] = 99
arr_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
arr_2d = np.arange(0,12)
arr_2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [77]:
arr_2d = arr_2d.reshape(3,4)

In [78]:
arr_2d.shape

(3, 4)

In [80]:
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [81]:
arr_2d[1,1]

5

In [82]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [83]:
arr = arr>4

In [84]:
arr


array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [86]:
arr = np.arange(0,10)

In [90]:
arr[arr>4]
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
import numpy as np
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])
dice_rolls[dice_rolls>2]

array([3, 5, 5, 5, 4, 4, 5, 3, 4, 5, 4, 6, 6, 3, 6, 3, 5, 6, 5])