In [2]:
import numpy as np

In [4]:
arr = np.arange(0,10)


In [5]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr - 2 

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [7]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
arr/arr

C:\Users\manje\AppData\Local\Temp\ipykernel_21188\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
1/0

ZeroDivisionError: division by zero

In [12]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [13]:
np.log(arr)

C:\Users\manje\AppData\Local\Temp\ipykernel_21188\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [14]:
arr.sum()

45

In [16]:
arr.var()

8.25

In [17]:
arr.std()

2.8722813232690143

In [18]:
arr2d = np.arange(0,25).reshape(5,5)

In [19]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
arr2d.sum()

300

In [27]:
arr2d.sum(axis=0) #addition across the rows

array([50, 55, 60, 65, 70])

In [26]:
arr2d.sum(axis=1) # addition across the columns

array([ 10,  35,  60,  85, 110])