# NumPy Arrays


In [1]:
import numpy as np

In [2]:
myList = [1, 2, 3, 4, 5]

In [3]:
type(myList)

list

In [4]:
np.array(myList)

array([1, 2, 3, 4, 5])

In [5]:
myList

[1, 2, 3, 4, 5]

In [6]:
myArr = np.array(myList)

In [7]:
type(myArr)

numpy.ndarray

In [8]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10,4)

array([0, 4, 8])

In [12]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.linspace(0,5,21) # 10 evenly spaced points from 0 to 10

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(2,2)

array([[0.57884854, 0.96493557],
       [0.71793037, 0.8272292 ]])

In [17]:
np.random.randn(5,5)

array([[-9.19948699e-01,  2.36339228e-01,  3.82332988e-01,
         4.97012598e-01,  1.08549382e+00],
       [-1.31026337e-01, -2.03841892e-01,  4.80606925e-01,
        -6.59871953e-01, -7.38265898e-01],
       [ 8.75314307e-02,  4.54109659e-01,  1.46209534e+00,
        -3.55023345e-01,  7.30055096e-01],
       [-1.64774049e+00, -2.80644929e-01,  2.83765153e-01,
        -5.67355314e-02,  4.77954006e-01],
       [ 1.96675803e+00, -2.95097777e-01,  5.72460647e-04,
        -4.52697404e-01,  2.60430151e-01]])

In [18]:
np.random.randint(1,100,(4,5))

array([[82, 22,  8, 31, 22],
       [36, 95, 87, 75, 42],
       [80, 11, 49,  3,  5],
       [69, 77,  2, 77, 83]])

In [19]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [24]:
arr = np.arange(0,25)

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
ranarr = np.random.randint(0,100,(4,2))
ranarr

array([[59, 20],
       [32, 75],
       [57, 21],
       [88, 48]])

In [33]:
ranarr.max()

88

In [34]:
ranarr.min()

20